- name: "Start and enable nginx"
  service:
    name: nginx
    state: started
    enabled: true
  become: true

- name: "Reload nginx"
  service:
    name: nginx
    state: reloaded
  become: true

- name: "Start and enable haproxy"
  service:
    name: haproxy
    state: started
    enabled: true
  become: true

- name: "Reload haproxy"
  service:
    name: haproxy
    state: reloaded
  become: true